source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target :'CloudPhotos' do
pod 'MJExtension'
pod 'MJRefresh'
pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'FMDB'
pod 'Masonry'
end
